title: Javalent's Plugins
description: The Description!
# Build settings
remote_theme: just-the-docs/just-the-docs@v0.4.0
markdown: Kramdown
plugins:
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-relative-links

url: plugins.javalent.com

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/just-the-docs.png"

# Set a path/url to a favicon that will be displayed by the browser
# favicon_ico: "/assets/images/favicon.ico"
# If the path to your favicon is /favicon.ico, you can leave favicon_ico unset.

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

# search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  # heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  # previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  # preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  # preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  # tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  # rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  # button: false

# mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  # version: "9.1.3"
  # Provide a path instead of a version key to load the mermaid library from a local file.

# Aux links for the upper right navigation
aux_links:
  "Javalent at Github":
    - "//github.com/valentine195"
  "Buy me a Coffee":
    - "//buymeacoffee.com/valentine195"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# External navigation links
nav_external_links:
  - title: I am an external Linku!
    url: https://github.com/just-the-docs/just-the-docs
    hide_icon: false # set to true to hide the external link icon - defaults to false


# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
#  markup / liquid-based content.
# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
# last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
# gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Edit this page on GitHub."
# gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the GitHub URL for your repo
# gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
# gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


# Callouts 
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  coming:
    title: Coming Soon
    color: pink
    opacity: 0.3
  retired:
    title: Retired
    color: red
    opacity: 0.5

# Define Jekyll collections
# collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  #tests:
  #  permalink: "/:collection/:path/"
  #  output: true

# just_the_docs:
  # Define which collections are used in just-the-docs
  # collections:
    # Reference the "tests" collection
    # tests:
      # Give the collection a name
      # name: Tests
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true


exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
